apiVersion: apps/v1
kind: Deployment
metadata:
  name: planet-prediction-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: planet-prediction-app
  template:
    metadata:
      labels:
        app: planet-prediction-app
    spec:
      containers:
        - name: planet-prediction-app
          image: akshat5302/planet_pred
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP

